version: '3.7'

services:
  webapp:    
    image: myregistry.co.uk/demo/webapp:1.0.0
    build: 
      context: .
      target: webapp
    ports:
      - "8080:80"

  runner:
    image: myregistry.co.uk/demo/runner:1.0.0
    build: 
      context: .
      target: runner
  