version: '3.7'

services:
  webapp:    
    image: myregistry.co.uk/demo/webapp:${VERSION}
    build: 
      context: .
      target: webapp
    ports:
      - "8080:80"
    environment:
      DEMO_Environment=prod
      DEMO_Version=${VERSION}

  runner:
    image: myregistry.co.uk/demo/runner:${VERSION}
    build: 
      context: .
      target: runner
  
